### ISSUE TITLE
About the time used for training and inference

### ISSUE THREAD

**Issue by Calvin-Pang** [jaroslaw1007/CLIT#1]
Hi I am quite interesting in this work and this is an absolutely great project. 
I have questions about the running efficiency and training time for CLIT since you used attention structure in the pipeline, which seems quite time-comsuming. So how much time do you spend in training and what about the inference time for the model?
Thanks a lot and wish you a nice week.

**Comment by jaroslaw1007** [comment]
Hi, thank you for your interest in our work.

As you say, attention structure is quite time-consuming due to the huge amount of operations.

Following training time statistics are provided with applying our setting. Unfortunately, the inference time is unstable results from the irregularly slowing down of our machines, so I cannot measure accurate inference time, instead, I could only give you an approximate range like 4-12 seconds per image.

Training time:
- EDSR-Baseline:
    - Stage 1 LIT: Avg. 2.4 minutes per epoch
    - Stage 2 CLIT: Avg. 4.0 minutes per epoch
    - Stage 3 CLIT: Avg. 4.3 minutes per epoch
- RDN:
    - Stage 1 LIT: Avg. 6.8 minutes per epoch
    - Stage 2 CLIT: Avg. 8.1 minutes per epoch
    - Stage 3 CLIT: Avg. 8.8 minutes per epoch
- SwinIR:
    - Stage 1 LIT: Avg. 9.2 minutes per epoch
    - Stage 2 CLIT: Avg. 11.0 minutes per epoch
    - Stage 3 CLIT: Avg. 13.0 minutes per epoch

**Comment by Calvin-Pang** [comment]
Thanks a lot for the reply! This is quite helpful for me.

**Comment by Alethiea-Cheng** [comment]
> Hi I am quite interesting in this work and this is an absolutely great project. I have questions about the running efficiency and training time for CLIT since you used attention structure in the pipeline, which seems quite time-comsuming. So how much time do you spend in training and what about the inference time for the model? Thanks a lot and wish you a nice week.



> Hi, thank you for your interest in our work.
> 
> As you say, attention structure is quite time-consuming due to the huge amount of operations.
> 
> Following training time statistics are provided with applying our setting. Unfortunately, the inference time is unstable results from the irregularly slowing down of our machines, so I cannot measure accurate inference time, instead, I could only give you an approximate range like 4-12 seconds per image.
> 
> Training time:
> 
> * EDSR-Baseline:
>   
>   * Stage 1 LIT: Avg. 2.4 minutes per epoch
>   * Stage 2 CLIT: Avg. 4.0 minutes per epoch
>   * Stage 3 CLIT: Avg. 4.3 minutes per epoch
> * RDN:
>   
>   * Stage 1 LIT: Avg. 6.8 minutes per epoch
>   * Stage 2 CLIT: Avg. 8.1 minutes per epoch
>   * Stage 3 CLIT: Avg. 8.8 minutes per epoch
> * SwinIR:
>   
>   * Stage 1 LIT: Avg. 9.2 minutes per epoch
>   * Stage 2 CLIT: Avg. 11.0 minutes per epoch
>   * Stage 3 CLIT: Avg. 13.0 minutes per epoch

Thanks for author yours really nice work, I am also highly interesting in it! A further question to previous and nice your reply. Are these statistics platform independent? (I believe on A100 or on RTX4090, there would be different on training and predicting time) Which and how many NVIDIA card did you used for these measurement?  Thank you!
